# Generated by Django 3.1.7 on 2021-02-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('khuser', '__first__'),
        ('product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('status', models.CharField(default='대기중', max_length=32, verbose_name='상태')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='등록날짜')),
                ('khuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khuser.khuser', verbose_name='사용자')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'db_table': 'hunit_order',
            },
        ),
    ]
